#!/usr/bin/perl

if (@ARGV > 1) {
	if ($ARGV[0] eq 'help') {
		help();
	}
}
else {
	run();
}

sub help {
	print qq~ 
[ help with tests ]
see readme
	~;	
}

sub run {
	system("make clean");
	system("make arch=i386");

	if (-e "os-image.bin")  {
		system("qemu-system-i386 --hda os-image.bin -d guest_errors,int");
	}
}
